import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabaseClient';
import type { Question } from '@/lib/data';

export async function GET() {
  const { data, error } = await supabase
    .from('questions')
    .select('*')
    .order('position', { ascending: true });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json(data);
}

export async function POST(request: Request) {
  try {
    const questions = await request.json();
    
    // `upsert` を使用して、存在しない場合は挿入、存在する場合は更新します。
    // Supabaseの `upsert` はデフォルトで `id` を衝突キーとして使用します。
    const { error } = await supabase
      .from('questions')
      .upsert(questions);

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (e) {
    if (e instanceof Error) {
      return NextResponse.json({ error: e.message }, { status: 500 });
    }
    return NextResponse.json({ error: 'An unknown error occurred' }, { status: 500 });
  }
}

export async function PATCH(request: Request) {
  try {
    const question: Question = await request.json();
    
    if (!question.id) {
      return NextResponse.json({ error: 'Question ID is required' }, { status: 400 });
    }

    // Omit fields that should not be updated directly or are generated by the DB
    const { created_at, ...updateData } = question;

    const { data, error } = await supabase
      .from('questions')
      .update(updateData)
      .eq('id', question.id)
      .select()
      .single(); // `.single()` to get a single object back, not an array

    if (error) {
      console.error('Supabase PATCH error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    if (!data) {
      return NextResponse.json({ error: 'Question not found or no changes made' }, { status: 404 });
    }

    return NextResponse.json(data); // Return the updated question
  } catch (e) {
    if (e instanceof Error) {
      return NextResponse.json({ error: e.message }, { status: 500 });
    }
    return NextResponse.json({ error: 'An unknown error occurred' }, { status: 500 });
  }
}